apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      param1:
        type: string
        default: qwerty
jobs:
  build:
    environment: AutoTestEnvironment
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
    needs:
      - test-approval
  test-approval:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: ff9892d6-0900-11ee-94c8-42010a83ae08
      disallowLaunchByUser: false
      notifyAllEligibleUsers: false
      instructions: ""
