apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      booparam:
        type: boolean
        default: false
      numberparam:
        type: number
        default: 1
        required: true
      choice:
        type: choice
        options:
          - opt1
        default: opt1
        required: true
      stringparam:
        type: string
        default: default string
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world asd"
