apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      number:
        type: number
  schedule:
    - cron: "*/3 * * * *"
  push:
    branches:
      - main
jobs:
  echo:
    steps:
      - uses: docker://corinne-container
        name: hello
        run: echo "boo"
