apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  pull_request:
    branches:
      - '**'
jobs:
  build:
    steps:
      - uses: cloudbees-io/lambda-create-function@v1
        name: Say d8d9
        with:
          timeout: ${{inputs.some}}
          publish: ${{inputs.some}}
          s3-object-version: some
          function-name: name
          dry-run: true
          iam-role-arn: aws name
